package com.kaustuv.poc.ws.service.greetings;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2013-03-30T11:00:04.994+05:30
 * Generated source version: 2.5.2
 * 
 */
@WebService(targetNamespace = "http://poc.kaustuv.com/ws/service/greetings", name = "Greetings")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface Greetings {

    @WebResult(name = "GreetingsResponse", targetNamespace = "http://poc.kaustuv.com/ws/service/greetings", partName = "parameterOut")
    @WebMethod(operationName = "Greetings", action = "Greetings")
    public GreetingsResponse greetings(
        @WebParam(partName = "parameterIn", name = "GreetingsRequest", targetNamespace = "http://poc.kaustuv.com/ws/service/greetings")
        GreetingsRequest parameterIn
    );
}
